apiVersion: core.oam.dev/v1alpha2
kind: Component
metadata:
  name: service-tracker-ui
spec:
  workload:
    apiVersion: core.oam.dev/v1alpha2
    kind: ContainerizedWorkload
    metadata:
      name: web-ui
    spec:
      osType: linux
      arch: amd64
      containers:
        - name: service-tracker-ui
          image: sonofjorel/rudr-web-ui:0.49   
          env:
            - name: FLIGHT_API_ROOT
              value: "foo"
            - name: WEATHER_API_ROOT
              value: "foo"
            - name: QUAKES_API_ROOT
              value: "foo"                  
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
  parameters:
    - name: flightsUri
      description: uri for flights-api pod
      required: true
      fieldPaths:
      - spec.containers[0].env[0].value
    - name: weatherUri
      description: uri for weather-api pod
      required: true
      fieldPaths:
      - spec.containers[0].env[1].value
    - name: quakesUri
      description: uri for quakes-api pod
      required: true
      fieldPaths:
      - spec.containers[0].env[2].value