# Human readable title of application.
title: Service Tracker

overviewShort: A sample application defined using the v1alpha2 OAM spec.
overview: |-
 Service Tracker is a sample application that displays a dashboard of weather, flights, and earthquakes.
 It is defined in accordance with the OAM v1alpha2 specification.
# Markdown description of this entry
readme: |-
 ### Create ServiceTrackers
 Before the application will provision, the Crossplane control cluster must
 be configured to connect to a provider (e.g. GCP, Azure, AWS, Alibaba).

 ```shell
 cat <<EOF | kubectl apply -f -
 apiVersion: oam.apps.crossplane.io/v1alpha1
 kind: ServiceTracker
 metadata:
   name: servicetracker-sample
 EOF
 ```
 The stack (and Crossplane) will take care of the rest.
# Maintainer names and emails.
maintainers:
- name: Dan Mangum
  email: dan@upbound.io
# Owner names and emails.
owners:
- name: Dan Mangum
  email: dan@upbound.io
# Human readable company name.
company: Crossplane
# Type of package: Provider, Stack, or Application
packageType: Application
# Keywords that describe this application and help search indexing
keywords:
- "samples"
- "examples"
- "tutorials"
- "oam"
# Links to more information about the application (about page, source code, etc.)
website: "https://crossplane.io"
source: "https://github.com/crossplane/app-wordpress"
# RBAC Roles will be generated permitting this stack to use all verbs on all
# resources in the groups listed below.
permissionScope: Namespaced
dependsOn:
- crd: "*.core.oam.dev/v1alpha2"
- crd: "kubernetesclusters.compute.crossplane.io/v1alpha1"
# License SPDX name: https://spdx.org/licenses/
license: Apache-2.0